import type { Vehicle, Operator, Trip } from '@/types';

export const vehicles: Vehicle[] = [
  {
    id: 'V001',
    licensePlate: 'UB-01-A4',
    model: 'Toyota Prius',
    operator: 'John Doe',
    status: 'Online',
    lastMaintenance: '2024-05-10',
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: 'V002',
    licensePlate: 'AB-CD-12',
    model: 'Honda Civic',
    operator: 'Jane Smith',
    status: 'Online',
    lastMaintenance: '2024-06-01',
    latitude: 37.7880,
    longitude: -122.4075,
  },
  {
    id: 'V003',
    licensePlate: 'XY-123-Z',
    model: 'Ford Transit',
    operator: 'Mike Johnson',
    status: 'Offline',
    lastMaintenance: '2024-04-22',
  },
  {
    id: 'V004',
    licensePlate: 'GH-45-KL',
    model: 'Tesla Model 3',
    operator: 'Emily White',
    status: 'Maintenance',
    lastMaintenance: '2024-07-15',
  },
  {
    id: 'V005',
    licensePlate: 'MN-67-OP',
    model: 'Toyota Camry',
    operator: 'Chris Green',
    status: 'Online',
    lastMaintenance: '2024-07-01',
    latitude: 37.7950,
    longitude: -122.4220,
  },
];

export const operators: Operator[] = [
  {
    id: 'O001',
    name: 'John Doe',
    role: 'Driver',
    shift: 'Day',
    status: 'Active',
  },
  {
    id: 'O002',
    name: 'Jane Smith',
    role: 'Driver',
    shift: 'Night',
    status: 'Active',
  },
  {
    id: 'O003',
    name: 'Mike Johnson',
    role: 'Driver',
    shift: 'Day',
    status: 'On Leave',
  },
  {
    id: 'O004',
    name: 'Emily White',
    role: 'Supervisor',
    shift: 'Day',
    status: 'Active',
  },
  {
    id: 'O005',
    name: 'Admin User',
    role: 'Admin',
    shift: 'Admin',
    status: 'Active',
  },
];

export const recentTrips: Trip[] = [
  {
    id: 'T001',
    customer: { name: 'Alice Williams', phone: '555-0101' },
    vehicle: vehicles[0],
    operator: operators[0],
    status: 'Completed',
    startTime: '2024-07-20T09:00:00Z',
    endTime: '2024-07-20T09:25:00Z',
    origin: '123 Main St',
    destination: '456 Oak Ave',
  },
  {
    id: 'T002',
    customer: { name: 'Bob Brown', phone: '555-0102' },
    vehicle: vehicles[1],
    operator: operators[1],
    status: 'In Progress',
    startTime: '2024-07-20T10:15:00Z',
    endTime: null,
    origin: '789 Pine Ln',
    destination: '101 Maple Dr',
  },
  {
    id: 'T003',
    customer: { name: 'Charlie Davis', phone: '555-0103' },
    vehicle: vehicles[4],
    operator: operators[2],
    status: 'Scheduled',
    startTime: '2024-07-20T11:00:00Z',
    endTime: null,
    origin: '212 Birch Rd',
    destination: '333 Cedar Blvd',
  },
    {
    id: 'T004',
    customer: { name: 'Diana Miller', phone: '555-0104' },
    vehicle: vehicles[0],
    operator: operators[0],
    status: 'Completed',
    startTime: '2024-07-20T11:30:00Z',
    endTime: '2024-07-20T11:50:00Z',
    origin: '555 Elm St',
    destination: '666 Willow Way',
  },
  {
    id: 'T005',
    customer: { name: 'Ethan Wilson', phone: '555-0105' },
    vehicle: vehicles[1],
    operator: operators[1],
    status: 'In Progress',
    startTime: '2024-07-20T12:05:00Z',
    endTime: null,
    origin: '777 Spruce Ave',
    destination: '888 Poplar Ct',
  },
  {
    id: 'T006',
    customer: { name: 'Fiona Garcia', phone: '555-0106' },
    vehicle: vehicles[4],
    operator: operators[2],
    status: 'Cancelled',
    startTime: '2024-07-20T13:00:00Z',
    endTime: null,
    origin: '999 Aspen Dr',
    destination: '111 Redwood Pkwy',
  },
];
