
import type { Vehicle, Operator, Trip, Customer, VehicleStatus } from '@/types';

export const customers: Customer[] = [
    { id: 'C001', name: 'Alice Williams', phone: '555-0101', pendingDebt: 0, notes: 'Prefers quiet rides. Please avoid talking too much.' },
    { id: 'C002', name: 'Bob Brown', phone: '555-0102', pendingDebt: 25.50, notes: 'Usually pays cash. Has a small dog carrier.' },
    { id: 'C003', name: 'Charlie Davis', phone: '555-0103', pendingDebt: 0 },
    { id: 'C004', name: 'Diana Miller', phone: '555-0104', pendingDebt: 0, notes: 'VIP customer. Always help with luggage.' },
    { id: 'C005', name: 'Ethan Wilson', phone: '555-0105', pendingDebt: 15.00 },
    { id: 'C006', name: 'Fiona Garcia', phone: '555-0106', pendingDebt: 0, notes: 'Student, destination is usually the university campus.' },
];

export const operators: Operator[] = [
  {
    id: 'O001',
    name: 'John Doe',
    role: 'Dispatcher',
    shift: 'Day',
    status: 'Active',
    servicesToday: 15,
    avgAssignmentTime: 5,
    maxIdleTime: 20,
    activeServices: 3,
  },
  {
    id: 'O002',
    name: 'Jane Smith',
    role: 'Dispatcher',
    shift: 'Night',
    status: 'Inactive',
    servicesToday: 12,
    avgAssignmentTime: 7,
    maxIdleTime: 15,
    activeServices: 2,
  },
  {
    id: 'O003',
    name: 'Mike Johnson',
    role: 'Dispatcher',
    shift: 'Day',
    status: 'Inactive',
    servicesToday: 0,
    avgAssignmentTime: 0,
    maxIdleTime: 0,
    activeServices: 0,
  },
  {
    id: 'O004',
    name: 'Emily White',
    role: 'Supervisor',
    shift: 'Day',
    status: 'Inactive',
    servicesToday: 0,
    avgAssignmentTime: 0,
    maxIdleTime: 0,
    activeServices: 0,
  },
  {
    id: 'O005',
    name: 'Admin User',
    role: 'Admin',
    shift: 'Admin',
    status: 'Active',
    servicesToday: 0,
    avgAssignmentTime: 0,
    maxIdleTime: 0,
    activeServices: 0,
  },
];

export let assignmentQueue: string[] = ['O001', 'O002']; // Operator IDs

export const vehicles: Vehicle[] = [
  {
    id: 'V001',
    name: 'Red Fury',
    unitNumber: '101',
    color: 'Red',
    licensePlate: 'UB-01-A4',
    model: 'Toyota Prius',
    operator: 'John Doe',
    status: 'En descanso',
    lastMaintenance: '2024-05-10',
    insuranceDueDate: '2025-01-15',
    latitude: -24.791, 
    longitude: -65.412,
  },
  {
    id: 'V002',
    name: 'Night Rider',
    unitNumber: '102',
    color: 'Black',
    licensePlate: 'AB-CD-12',
    model: 'Honda Civic',
    operator: 'Jane Smith',
    status: 'Ocupado',
    lastMaintenance: '2024-06-01',
    insuranceDueDate: '2025-03-20',
    latitude: -24.780, 
    longitude: -65.411,
  },
  {
    id: 'V003',
    name: 'The Ghost',
    unitNumber: '103',
    color: 'White',
    licensePlate: 'XY-123-Z',
    model: 'Ford Transit',
    operator: 'Mike Johnson',
    status: 'Fuera de servicio',
    lastMaintenance: '2024-04-22',
    insuranceDueDate: '2024-11-30',
  },
  {
    id: 'V004',
    name: 'Crimson Bolt',
    unitNumber: '201',
    color: 'Red',
    licensePlate: 'GH-45-KL',
    model: 'Tesla Model 3',
    operator: 'Emily White',
    status: 'Mantenimiento',
    lastMaintenance: '2024-07-15',
    insuranceDueDate: '2024-09-01',
  },
  {
    id: 'V005',
    name: 'Black Pearl',
    unitNumber: '202',
    color: 'Black',
    licensePlate: 'MN-67-OP',
    model: 'Toyota Camry',
    operator: 'Chris Green',
    status: 'Libre',
    lastMaintenance: '2024-07-01',
    insuranceDueDate: '2025-02-28',
    latitude: -24.796, 
    longitude: -65.425,
  },
    {
    id: 'V006',
    name: 'Blue Thunder',
    unitNumber: '301',
    color: 'Blue',
    licensePlate: 'QR-89-ST',
    model: 'Hyundai Ioniq',
    operator: 'Alex Ray',
    status: 'En camino',
    lastMaintenance: '2024-07-10',
    insuranceDueDate: '2025-04-10',
    latitude: -24.785,
    longitude: -65.420,
  },
  {
    id: 'V007',
    name: 'Orange Comet',
    unitNumber: '302',
    color: 'Orange',
    licensePlate: 'UV-10-WX',
    model: 'Kia Niro',
    operator: 'Sam Bee',
    status: 'En espera',
    lastMaintenance: '2024-06-20',
    insuranceDueDate: '2025-05-18',
    latitude: -24.775,
    longitude: -65.405,
  },
];

export const recentTrips: Trip[] = [
  {
    id: 'T001',
    customer: customers[0],
    vehicle: vehicles[0],
    operator: operators[0],
    status: 'Completed',
    requestTime: '2024-07-20T09:00:00Z',
    scheduledTime: null,
    endTime: '2024-07-20T09:25:00Z',
    origin: 'Av. del Bicentenario de la Batalla de Salta 702, Salta',
    destination: 'Caseros 670, Salta',
    originCoords: [-65.4093, -24.7813],
    destinationCoords: [-65.4110, -24.7891],
    notes: 'Pick up at the main entrance. The client is waiting with a blue suitcase.',
    price: 15.75,
  },
  {
    id: 'T002',
    customer: customers[1],
    vehicle: vehicles[1],
    operator: operators[1],
    status: 'In Progress',
    requestTime: '2024-07-20T10:15:00Z',
    scheduledTime: null,
    endTime: null,
    origin: 'Gral. Martin Güemes 500, Salta',
    destination: 'Plaza 9 de Julio, Salta',
    originCoords: [-65.4075, -24.7865],
    destinationCoords: [-65.4102, -24.7888],
    price: 22.50,
  },
  {
    id: 'T003',
    customer: customers[2],
    vehicle: vehicles[5],
    operator: operators[0],
    status: 'Assigned',
    requestTime: '2024-07-20T11:00:00Z',
    scheduledTime: null,
    endTime: null,
    origin: 'Virrey Toledo 1300, Salta',
    destination: 'Monumento a Güemes, Salta',
    originCoords: [-65.4190, -24.7788],
    destinationCoords: [-65.4077, -24.7946],
    notes: 'The street is under construction, it is necessary to enter through the parallel one.',
    price: 18.00,
  },
    {
    id: 'T004',
    customer: customers[3],
    vehicle: vehicles[0],
    operator: operators[0],
    status: 'Completed',
    requestTime: '2024-07-20T11:30:00Z',
    scheduledTime: null,
    endTime: '2024-07-20T11:50:00Z',
    origin: 'A. Saravia 200, Salta',
    destination: 'Mercado Artesanal de Salta',
    originCoords: [-65.4045, -24.7871],
    destinationCoords: [-65.4147, -24.7905],
    price: 12.25,
  },
  {
    id: 'T005',
    customer: customers[4],
    vehicle: null,
    operator: null,
    status: 'Scheduled',
    requestTime: '2024-07-21T12:00:00Z',
    scheduledTime: '2024-07-22T09:00:00Z',
    endTime: null,
    origin: 'Paseo de los Poetas, Salta',
    destination: 'Catedral Basílica de Salta',
    originCoords: [-65.4069, -24.7917],
    destinationCoords: [-65.4108, -24.7890],
    price: 25.00,
  },
  {
    id: 'T006',
    customer: customers[5],
    vehicle: vehicles[4],
    operator: operators[0],
    status: 'Cancelled',
    requestTime: '2024-07-20T13:00:00Z',
    scheduledTime: null,
    endTime: null,
    origin: 'Estadio Padre Ernesto Martearena, Salta',
    destination: 'Parque San Martín, Salta',
    originCoords: [-65.4101, -24.8322],
    destinationCoords: [-65.4181, -24.7932],
    price: 0,
  },
  {
    id: 'T007',
    customer: customers[0],
    vehicle: null,
    operator: null,
    status: 'In Tray',
    requestTime: '2024-07-21T14:00:00Z',
    scheduledTime: null,
    endTime: null,
    origin: 'Terminal de Omnibus de Salta',
    destination: 'Aeropuerto Internacional de Salta',
    originCoords: [-65.4208, -24.7981],
    destinationCoords: [-65.4870, -24.8465],
    notes: 'The customer has a lot of luggage, help is required.',
    price: 35.50,
  }
];
